let headingtext = "<h2>A Page of JavaScript</h2>";
let myintro = "Hello! welcome to my JavaScript page!";
let linktag = "<a href = \"http://www.pageresource.com\">Link to a site</a>";
let redtext = "<span style = \"color:red\">I am so colorful today!</span>";
let begineffect = "<em>";
let endeffect = "</em>";
let beginpara = "<p>";
let endpara = "</p>";
document.write(headingtext);
document.write(begineffect + myintro + endeffect);
document.write(beginpara);
document.write(linktag);
document.write(endpara);
document.write(beginpara);
document.write(redtext);
document.write(endpara);
